language: c
script:
# Toolchain Choice
# This will clone TeamVee Prebuilt Toolchains in directory described in build.sh
#
# Branchs available is:
# Google Branch is "google_gcc" | (1) 4.7 / (2) 4.8
# Linaro Branch is "linaro_gcc" | (1) 4.8.4 / (2) 4.9.4

# Toolchain select here is Google 4.7
- export ntoolchainbranch="google_gcc"
- export ntoolchainchoice="1"
- git clone -b "${ntoolchainbranch}" "https://github.com/TeamVee/android_prebuilt_toolchains" "../android_prebuilt_toolchains"

# This will call build.sh with following parameters inside ${nbasebuildsh}:
#
# 'export ndevicechoice="#"'
# 'export nbasebuildsh="23${ndevicechoice}4${ntoolchainchoice}56q"'
# 'source build.sh <<< "${nbasebuildsh}"'
# 'export zipfile#="${zipfile}"'
#
# First "2" is "Clean Kernel"
# Second "3" is "Device Choice"
# ${ndevicechoice} is "Number of Choice under Device Choice"
# Fourth "4" is "Toolchain Choice"
# ${ntoolchainchoice} is "Number of Toolchain under Toolchain Choice"
# Sixth "5" is "Build Kernel"
# Seventh "6" is "Zip the kernel and Modules"
# Last "q" is to Exit of Script

# For Sony Xperia E1 Single | D2004/D2005 | 20.1.B.2.15
- export ndevicechoice="0"
- export nbasebuildsh="23${ndevicechoice}4${ntoolchainchoice}56q"
- source build.sh <<< "${nbasebuildsh}"
- export zipfile0="${zipfile}"
# For Sony Xperia E1 Dual | D2104/D2105 | 20.1.B.2.15
- export ndevicechoice="1"
- export nbasebuildsh="23${ndevicechoice}4${ntoolchainchoice}56q"
- source build.sh <<< "${nbasebuildsh}"
- export zipfile1="${zipfile}"
# For Sony Xperia E1 TV | D2114 | 20.1.B.0.65
- export ndevicechoice="2"
- export nbasebuildsh="23${ndevicechoice}4${ntoolchainchoice}56q"
- source build.sh <<< "${nbasebuildsh}"
- export zipfile2="${zipfile}"
branches:
  except:
    - stock
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    # Install Travis APP:
    # "gem install travis"
    #
    # Then, you can use encrypt command to encrypt data:
    # "travis encrypt SOMEVAR=secretvalue"
    #
    # This will output a string looking something like:
    # 'secure: ".... encrypted data ...."'
    #
    # Just change this value with your Passwork key encrypted
    secure: "tawcLRz5Bm2bgRexze2Zol3pYZqZKe7cwhhDs46TdHMrcrEuMX6bijYTiCYKy/1rLAHr8NGIQOBBF4LXIMouBcQYpzgzlRpFRl6z6NfJOEtXJ3fvyr0JQOOX7QkG7acDnURBHXroI7b+wK4e6f/An9S/1vgSrBKvrYJlQk8OYEt78aOp9GioblvgzfUJx/ZCxvDYSe5dpXuKFBoZyinPuK83ICyWrRViDqVI3JUMo3TPBrTQ/27olNGuoEjZxjU3fATBDc2Im/kZaxoh59OqT4jjKW6i2dDW/GUm5Nl8SxyxRCBCbzGDgCmtXZ4yuqvO5TCsAoPPD4ksZbeywbeHVVViAlsS8majZLedMWwlERL+pW6v9NneaUH+D44881Cq19AepnLq/Oew4F3u6XXqlm69Is3YyJ2WXKqONwa4rbxUyF2hHf2b4bzz7guMtf/MKf/7T4pMKBH6gpRQlD6A9NNS8zhaI5vPzl0B2cPwq9kYPt3DUfWDTxUHi7jztnzja5jk8jXT6DDbNKOqtM7e5In3Hhe0qzbeBYLKyyjwgEoSlsdO6mut6DE4iyRWtbc3MUL+q4O0YDNrvUebuuwxX+PkJwTob0EBlDDLmNpuamhnIFFmjvFWkES86MyId+HGrGrmF2OU6HgAoIITd2FhfYj9Z/C0V00G7cQ2jhCX9eg="
  file:
    - "zip-creator/${zipfile0}"
    - "zip-creator/${zipfile1}"
    - "zip-creator/${zipfile2}"
  on:
    tags: true
